# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ContactApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SVProgressHUD'
  pod 'SwiftyContacts' , '~> 2.0.7'
  pod 'SnapKit'
  pod 'ESPullToRefresh'

end
